# 创建集群私密功能的集群角色：秘钥只读
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # 集群级别 无需 namespace
  name: secret-reader
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list"]

# 创建特定权限的角色：pod只读
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: default # namespace级别
rules:
  - apiGroups: [""] # "" 指定核心 API 组
    resources: ["pods"] # 指定此权限的作用的资源类型
    verbs: ["get", "watch", "list"] # 指定权限

# 创建账户
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kk
  namespace: default

# 将角色绑定到用户，使得用户具备相应角色的权限
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: default
subjects: # 用户主体
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: kk # 用户名
roleRef: # 绑定的角色
  kind: Role # 确定 Role 或 ClusterRole 的类型
  name: pod-reader # 指定要绑定的 Role 或 ClusterRole 的名称
  apiGroup: rbac.authorization.k8s.io
