apiVersion: v1
kind: ConfigMap
metadata:
  name: special-config
data: # 字面值创建
  special.how: very
  special.type: charm2

# 作为容器的环境变量
---
apiVersion: v1
kind: Pod
metadata:
  name: configmap-as-env
spec:
  containers:
    - name: busybox-env
      image: busybox
      command: [ "sleep", "10000" ]
      # 引用 configmap 的全部值
      envFrom:
        - configMapRef:
            name: special-config # 和 ConfigMap 的 metadata.name 一直
      env: # 引用某个值，赋值给某个环境变量
        - name: SPECIAL_TYPE_KEY
          valueFrom:
            configMapKeyRef:
              name: special-config
              key: special.type

# 使用存储在 ConfigMap 中的数据填充数据卷
---
apiVersion: v1
kind: Pod
metadata:
  name: configmap-as-vol
spec:
  # 挂载 configmap
  volumes:
    - name: config-volume
      configMap:
        name: special-config # 和 ConfigMap 的 metadata.name 一直
  containers:
    - name: busybox-vol
      image: busybox
      command: [ "sleep", "10000" ]
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config

