apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  # value 必须是base64 编码
  password: MWYyZDF1MmU2N2Rm # 明文 1f2d1u2e67df
  username: YWRtaW4=

# Opaque 秘钥挂载到导入
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    name: seret-test
  name: seret-test
spec:
  volumes:
    # 导入secret
    - name: secrets
      secret:
        secretName: mysecret
  containers:
    - image: tomcat:9.0.20-jre8-alpine
      name: tomcat9
      # mounts中使用volume中的secret
      volumeMounts:
        - name: secrets # 导入的秘钥
          mountPath: "/etc/secrets" # 挂载的路径
          readOnly: true

---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
spec:
  containers:
    - name: mysql
      image: mysql:8.0
      # 将secret的值赋给环境变量
      env:
        - name: db-user
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: username
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password
