apiVersion: v1
kind: Pod
metadata:
  name: node-affinity-pod
spec:
  containers:
    - name: node-affinity-ctn
      image: busybox
      command: [ "sleep", "10000" ]
  affinity:
    nodeAffinity: # 节点亲和性
      requiredDuringSchedulingIgnoredDuringExecution: # 硬策略
        nodeSelectorTerms: # 强制匹配节点的标签
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - docker-desktop # ✅本地可部署
                  - docker-desktop2 # ⚠️本地不可部署
