apiVersion: v1
kind: Pod
metadata:
  name: liveness-probe-tcp
spec:
  containers:
    - name: nginx
      image: nginx
      livenessProbe:
        initialDelaySeconds: 5
        timeoutSeconds: 1
        tcpSocket:
          port: 80
