
apiVersion: v1
kind: Pod
metadata:
  name: readiness-http-pod
  namespace: default
spec:
  containers:
    - name: readiness-http-container
      image: nginx:1.17.10-alpine
      readinessProbe:
        httpGet:
          port: 80
#          path: /index.html # 正常
          path: /index1.html # 失败，不存在的页面
        initialDelaySeconds: 1
        periodSeconds: 3
