apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello-cjob
spec:
  schedule: "*/1 * * * *" # 每1min执行
  jobTemplate: # job 模板
    spec:
      template: # pod 模板
        spec:
          restartPolicy: OnFailure
          containers:
            - name: hello
              image: busybox
              args:
                - /bin/sh
                - -c
                - date; echo Hello from the Kubernetes cluster
