---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: nginx # 必须的headless service
  podManagementPolicy: Parallel
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  # PV/PVC 模板
  volumeClaimTemplates:
    - metadata:
        name: www
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
  # Pod 模板
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          volumeMounts: # 和 spec.volumeClaimTemplates[0].metadata.name 一致
            - name: www
              mountPath: /usr/share/nginx/html
          ports:
            - containerPort: 80
              name: web
