# 每个节点运行一个 Nginx 守护服务
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemonset
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx-daemonset-tmpl
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-daemonset
          image: nginx:1.17.10-alpine
