apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
spec:
  replicas: 4
  selector: # 标签选择器
    matchLabels: # 比RC新增的标签选择器
      app: nginx # 和 spec.template.metadata.labels.app 一致
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
